version: '3.8'

services:

  api :
    build : ./api
    container_name : api
    ports:
      - "5000:5000"
    depends_on :
      - mongo

  front :
    build : ./front
    container_name : front
    ports:
      - "3000:3000"
    stdin_open : true
    tty : true
    restart: always
    depends_on :
      - api
    volumes :
      - ./front/src:/app/src


  mongo :
    image : "mongo"
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "tatams"
      MONGO_INITDB_ROOT_PASSWORD: " "

volumes:
  data:
    

    
  